<?php

namespace app\controllers;

use app\models\Box;
use app\models\Order;
use app\models\Review;
use app\models\User;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\Response;
use app\models\LoginForm;

class SiteController extends CController
{
	public function behaviors()
	{
		return ArrayHelper::merge(
			parent::behaviors(),
			[
				'access' => [
					'class' => AccessControl::class,
					'rules' => [
						[
							'allow' => true,
							'actions' => ['login'],
							'roles' => ['?'],
						],
						[
							'allow' => true,
							'actions' => ['index', 'get-reservation-box-form', 'send-review', 'send-review-validate'],
							'roles' => [],
						],
						[
							'allow' => true,
							'actions' => ['logout','set-reservation-box','get-my-reservation-form', 'cancel-my-reservation'],
							'roles' => ['@'],
						],
					],
				],
				[
					'class' => 'yii\filters\AjaxFilter',
					'only' => ['login', 'get-reservation-box-form', 'get-box-timetable', 'get-my-reservation-form', 'send-review', 'send-review-validate'],
					'errorMessage' => 'Ошибка типа запорса (AJAX ONLY!)',
				],
			]
		);
	}

    public function init()
    {
        Yii::$app->components['assetManager'] = [
            'bundles' => [
                'yii\bootstrap\BootstrapAsset' => [
                    'css' => false,
                ],
            ],
        ];

        parent::init(); // TODO: Change the autogenerated stub
    }

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
		return $this->render('index');
	}

	/**
	 *  Send review from user
	 * @return string
	 */
	public function actionSendReview()
	{
		$model = new Review();
		if ($model->load(Yii::$app->getRequest()->post())) {
				if ($model->validate() && $model->save()){
					$this->ajaxResult->data = "Ваше сообщение отправлено на модерацию";
				}
		}
		$this->ajaxResult->error = $model->hasErrors() ? Html::errorSummary($model) : null;
	}

	/**
	 *  Send review from user [validate]
	 * @return string
	 */
	public function actionSendReviewValidate()
	{
		Yii::$app->response->format = Response::FORMAT_JSON;
		$model = new Review;
		if (Yii::$app->getRequest()->isPost && $model->load(Yii::$app->getRequest()->post())) {
			return ActiveForm::validate($model);
		}
	}

	/**
	 * Displays error page.
	 *
	 * @return string
	 */
	public function actionErrorPage()
	{
		$this->layout = 'admin';
		$exception = Yii::$app->errorHandler->exception;
		if ($exception !== null) {
			if (Yii::$app->request->isAjax){
				$this->ajaxResult->error =  $exception->getMessage();
			} else {
				return $this->render('error', ['exception' => $exception]);
			}
		}
	}

	/**
	 * Login action.
	 *
	 * @return Response|string
	 */
	public function actionLogin()
	{
		$model = new LoginForm();
		if (Yii::$app->request->isPost){
			if ($model->load(Yii::$app->request->post()) && $model->validate()) {
				$model->smsPhone = str_replace([' ' , '(' , ')', '-', '+'] , '' , $model->smsPhone);
				if ($model->smsCode){
					if ($model->login()) {
						$this->ajaxResult->data = Yii::$app->user->identity->username;
						if (User::checkAccess([User::ROLE_ADMIN, User::ROLE_OPERATOR])){
							$this->ajaxResult->data = 'admin';
						}
					}
				} else {
					$this->ajaxResult->notify =  'Пароль подтверждения отправлен на телефон ' . $model->smsPhone;
					$model->sendPhoneSMS($model->smsPhone);
				}
			}
			//return ActiveForm::validate($model);
			$this->ajaxResult->error = $model->hasErrors() ? Html::errorSummary($model, ['header'=>'']) : null;

		} else {
			return $this->renderAjax('login', [
				'model' => $model,
			]);
		}
	}

	/**
	 * @return array
	 * @internal param null $date
	 */
	public function actionGetMyReservationForm()
	{
		$dataProvider = new ActiveDataProvider([
			'query' => Order::find()->where(['user_id'=>\Yii::$app->user->id, 'status' => Order::STATUS_BUSY])->orderBy(['date_start'=>SORT_DESC,'time_start'=>SORT_DESC]),
			'pagination' => [
				'pageSize' => 5,
			],
			'sort' => false
		]);
		if (\Yii::$app->request->get('no-pjax')){
			return $this->renderPartial('/user/myReservationBoxForm', ['orders' => $dataProvider]);
		} else {
			return $this->renderAjax('/user/myReservationBoxForm', ['orders' => $dataProvider]);
		}
	}

	/**
	 * @return array
	 */
	public function actionGetReservationBoxForm()
	{
		$orderData = Yii::$app->getRequest()->get();
		$order = new Order();
		$order->load($orderData);
		$order->date_time_start = date('Y-m-d H:i', strtotime($order->date_start . ' ' . $order->time_start));
		$order->user_id = \Yii::$app->user->id;
        if (!$order->box_id){
            $firstBox =  Box::find()->one();
            $order->box_id = $firstBox->id;
        }
        $availableServices = \app\models\Box::getAvailableServices($order->box_id, $order->date_time_start)->models;
		return $this->renderAjax('/order/reservationBoxForm', ['order' => $order,'availableServices' => $availableServices]);
	}
	/**
	 * @return array
	 */
	public function actionSetReservationBox()
	{
		$model = new Order();
		if ($model->load(Yii::$app->getRequest()->post())) {
			$model->user_id = \Yii::$app->user->id;
			$model->money_cost = $model->service->money_cost;
            if ($model->date_time_start) {
                $model->date_start = date('Y-m-d', strtotime($model->date_time_start));
                $model->time_start = date('H:i', strtotime($model->date_time_start));
            } else {
                $model->date_time_start = $model->date_start . ' ' . $model->time_start;
            }
			$timeEnd = strtotime($model->date_time_start) + strtotime($model->service->time_processing) - strtotime("00:00:00");
			// проверка переполнения времени
			if (date('Y-m-d',strtotime($model->date_time_start)) != date('Y-m-d', $timeEnd)){
				$timeEnd = strtotime("23:59:59");
			}
			$model->time_end = date('H:i', $timeEnd);
			if (User::checkAccess([User::ROLE_USER])){
			}
			if ($model->validate() && $model->save()){
				$this->ajaxResult->data = "Спасибо, запись произведена #" . $model->id;
			}
		}
		$this->ajaxResult->error = $model->hasErrors() ? Html::errorSummary($model) : null;
	}

	/**
	 * Logout action.
	 *
	 * @return Response
	 */
	public function actionLogout()
	{
		Yii::$app->user->logout();

		return $this->goHome();
	}

	/**
	 * @param $id
	 */
	public function actionCancelMyReservation($id)
	{
		Order::updateAll(['status'=>Order::STATUS_CANCEL],['id'=>$id, 'user_id'=>\Yii::$app->user->id]);
        return $this->actionGetMyReservationForm();
	}


}
